
server:
  port: 8770

spring:
  application:
    name: user
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/admin
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
