version: '3'
services:
  mongodb:
    image: mongo:3.5
    hostname: localhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db