
server:
  port: 8762

spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://test:123456@192.168.3.129:27017/hi
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      defaultBinder: defaultRabbit
      bindings:
        input:
          description: stream-rabbitmq-product
          contentType: application/json
          binder: defaultRabbit
          group: srms-group
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: srms-key.*
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: wifidns.top
                port: 5672
                username: rabbitmq
                password: rabbitmq
                virtual-host: /
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
