
server:
  port: 8762

spring:
  application:
    name: product
  data:
    mongodb:
      uri: mongodb://test:123456@localhost:27017/test
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
