version: '3'
services:
  mongodb:
    image: mongo:3.5
    container_name: srms_mongodb
    hostname: localhost
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: srms_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"